target-version = "py311"
line-length = 120

[lint]
select = ["ALL"]
ignore = [
    "D103", 
    "TD002", 
    "TD003", 
    "T201", 
    "DTZ007", 
    "D203", 
    "D212", 
    "COM812", 
    "ERA001", 
    "DTZ006", 
    "D101", 
    "TRY003", 
    "EM101", 
    "PLR0911",
    "D100",
    "SIM300",
    "SIM110",
]

[lint.isort]
force-single-line = true
